### ISSUE TITLE
Client can't send packets

### ISSUE THREAD

**Issue by infinitapple** [dlgudwn94/Googler#10]
![a6](https://cloud.githubusercontent.com/assets/26422375/24864002/e3fa0a96-1e3d-11e7-86f4-a08adea36082.JPG)

클라이언트 파일에서 패킷을 보낼때마다 "send"문자열을 출력하도록 했는데,
56320바이트 파일을 보낼때 패킷(1024바이트)을 2개밖에 보내지 않습니다.

**Comment by LeeSangMin0329** [comment]
일해라 이형주
