### ISSUE TITLE
In FileStream, Please follow the protocol.

### ISSUE THREAD

**Issue by infinitapple** [dlgudwn94/Googler#11]
![a4](https://cloud.githubusercontent.com/assets/26422375/24864214/748eb3ae-1e3e-11e7-954a-6d5fc757f19b.JPG)
처음으로 보내는 패킷에는 파일 사이즈가 아니라 파일 이름을 보내주면 좋겠습니다.

**Comment by LeeSangMin0329** [comment]
일해라 이형주
