### ISSUE TITLE
Encapsulation Problem

### ISSUE THREAD

**Issue by LeeSangMin0329** [dlgudwn94/Googler#7]
그냥 네트워크에서 파일스트림 인스턴스화해서 만드려고했는데,
확장성을 고려하면 네트워크에서 파일관련클래스를 만지는게 좀 아닌거 같음.

**Comment by infinitapple** [comment]
그럼 파일 스트림 클래스를 새로 작성할게

**Comment by infinitapple** [comment]
헤더랑 cpp 파일을 새로 작성하는게 좋을까 아니면 기존 파일에 작성할까?

**Comment by LeeSangMin0329** [comment]
기능별로 클래스를 나누는게 취지니까 새로 작성하는게 좋지

**Comment by infinitapple** [comment]
네트워크헤더에서 파일스트림 헤더를 참조하는 구조로 재작성 할게

**Comment by infinitapple** [comment]
일단 FileManage 클래스를 새로 만들었어.
보완 사항 있으면 추가로 말해줘.

**Comment by infinitapple** [comment]
수정된 구현사항으로는 서버측에서 받을때 파일명을 지정하고 서버를 여는 방식인데,
그러면 파일 하나를 받기 위해서 서버를 여는것 같이 되버리지 않아?
확장성을 고려하면 파일명도 클라이언트 측에서 받아와야 할 것 같은데.

**Comment by LeeSangMin0329** [comment]
그건 파일 다루는데서 할 선택사항이지 난 니가만든거 갓다 썻을뿐
